fn main() {
// Opération n°0 :
let pub mut var1: i64 = 6799816953675316739
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	!var1;

// Opération n°1 :
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	var1;
	!var1;

// Opération n°2 :
let pub mut var2: u64 = 15155949864827097968
let pub mut var3: i8 = -88
let pub mut var4: u16 = 14557
let pub mut var5: i64 = 2290839106981062234
let pub mut var6: i16 = 24218
let pub mut var7: u64 = 15065997681027834618
let pub mut var8: i64 = 4341950821392113952
let pub mut var9: u32 = 702643973
let pub mut var10: u8 = 67
let pub mut var11: bool = true
	var2;
	var3;
	var4;
	var5;
	var6;
	var7;
	var8;
	var9;
	var10;
	-var11;

// Opération n°3 :
	var8;
	var4;
	var4;
	var5;
	var5;
	var6;
	var1;
	var2;
	var8;
	!var6;

// Opération n°4 :
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	-var11;

// Opération n°5 :
	var5;
	var7;
	var4;
	var10;
	var4;
	var9;
	var1;
	var5;
	var10;
	!var4;

// Opération n°6 :
	var5;
	var7;
	var2;
	var10;
	var3;
	var7;
	var1;
	var3;
	var1;
	!var10;

// Opération n°7 :
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	-var11;

// Opération n°8 :
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	var11;
	-var11;

// Opération n°9 :
	var7;
	var1;
	var3;
	var5;
	var1;
	var2;
	var9;
	var7;
	var10;
	!var8;

}
